fullDescription: ''
closing: |
  ## How to Install
  Read about how to install any packages from the `Unity Game Framework` registry: [Install Package](https://github.com/unity-game-framework/ugf-documentation/wiki/Install-Package).
footer: |
  ---
  > Unity Game Framework | Copyright 2020