- name: Archived
  description: An issue no longer relevant, but can be reopened.
  color: dddddd
- name: Bug
  description: Mentioned in changelog under the Fixed section.
  color: ffbbbb
- name: Change
  description: Mentioned in changelog under the Changed section.
  color: bbbbff
- name: Deprecation
  description: Mentioned in changelog under the Deprecated section.
  color: dddddd
- name: Feature
  description: Mentioned in changelog under the Added section.
  color: bbffbb
- name: Remove
  description: Mentioned in changelog under the Removed section.
  color: dddddd
- name: Security
  description: Mentioned in changelog under the Security section.
  color: dddddd